apiVersion: apps/v1
kind: Deployment
metadata:
  name: pks-monitor
  namespace: monitoring
  labels:
    app: pks-monitor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pks-monitor
  template:
    metadata:
      name: pks-monitor
      namespace: monitoring
      labels:
        app: pks-monitor
    spec:
      volumes:
        - name: certs
          secret:
            secretName: pks-api-cert
      containers:
        - image: "victorpupim/pks-monitor:1.0.0"
          name: pks-monitor
          imagePullPolicy: Always
          env:
            - name: PKS_API
              valueFrom:
                secretKeyRef:
                  key: pks-api
                  name: pks-api-monitor
            - name: UAA_CLI_ID
              valueFrom:
                secretKeyRef:
                  name: pks-api-monitor
                  key: uaa-cli-id
            - name: UAA_CLI_SECRET
              valueFrom:
                secretKeyRef:
                  name: pks-api-monitor
                  key: uaa-cli-secret
          volumeMounts:
            - name: certs
              mountPath: /etc/pks-monitor/certs
              readOnly: true
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          lifecycle:
            preStop:
              httpGet:
                port: 8080
                path: "/prestop"
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: pks-monitor
  namespace: monitoring
  labels:
    app: pks-monitor
    release: monitoring
    jobLabel: pks-monitor
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9190
      targetPort: 8080
      protocol: TCP
  selector:
    app: pks-monitor

#---
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  name: pks-monitor
#  labels:
#    app: pks-monitor
#    release: "monitoring"
#spec:
#  selector:
#    matchLabels:
#      app: pks-monitor
#      release: monitoring
#  endpoints:
#    - port: http-metrics
#      interval: 1m
#      scrapeTimeout: 30s
